#!/bin/bash
# inject-shell-test-reminder.sh — PreToolUse nudge on Edit/Write/NotebookEdit
# of any *.sh file (excluding *.test.sh). Replaces the always-loaded
# CLAUDE.md "Every .sh script MUST ship with a sibling .test.sh" block with
# a context-aware injection — only fires when relevant.
# Exit 0 always — emits additionalContext, never blocks.
# Soft enforcement only: many .sh files live outside git, so commit-time
# pairing is structurally impossible — see require-tests.sh which handles
# Java/Go/TS/Python where git-cached pairing works.
source "$(dirname "$0")/path-bootstrap.sh"

if ! command -v jq &> /dev/null; then
  exit 0
fi

INPUT=$(cat)
TOOL=$(echo "$INPUT" | jq -r '.tool_name // empty')

case "$TOOL" in
  Edit|Write|NotebookEdit) ;;
  *) exit 0 ;;
esac

FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

# Filename gate: must end in .sh AND must NOT be *.test.sh.
# Adversarial benign inputs to verify against: foo.sh.bak (no), foo.shtml (no),
# foo.test.sh (no — test files satisfy the rule themselves), .sh-name.txt (no).
case "$FILE_PATH" in
  *.test.sh) exit 0 ;;
  *.sh) ;;
  *) exit 0 ;;
esac

# Determine sibling test path to tailor the message.
SIBLING="${FILE_PATH%.sh}.test.sh"
BASE=$(basename "$FILE_PATH")
if [ -f "$SIBLING" ]; then
  SIBLING_STATE="EXISTS at ${SIBLING} — review whether this change needs new/updated test cases; do NOT commit source-only"
  SM="🧪 ${BASE} · test sibling exists — update if behavior changed"
else
  SIBLING_STATE="DOES NOT EXIST — you MUST create ${SIBLING} alongside this change"
  SM="🧪 ${BASE} · test sibling MISSING — create $(basename "$SIBLING")"
fi

REMINDER=$(cat <<EOF
SHELL TEST DISCIPLINE — editing ${FILE_PATH}.

REQUIRED before this script is considered ready:
- Every .sh with testable behavior MUST ship with a sibling *.test.sh. Sibling here: ${SIBLING_STATE}.
- Minimum coverage per .sh: ≥1 false-positive case (input that LOOKS like the trigger but is benign), ≥1 normal-safe case, ≥2 trigger cases, ≥1 edge case (2>&1 for redirect hooks, escaped placeholders for substitution hooks, empty input, etc.).
- Tests MUST source \$HOME/.claude/_lib/test-helpers.sh and resolve script-under-test via HOOK="\$(_test_script_dir "\$0")/foo.sh" then _require_executable "\$HOOK". NEVER \$(dirname "\$0") directly — relative \$0 breaks subshell cd and produces mystery test failures.
- Each test = ONE independent invocation via mocked stdin. No shared state across cases.
- bash <script>.test.sh MUST exit 0 (all pass) before the script ships. Run all tests via bash \$HOME/.claude/_lib/run-all-tests.sh (canonical entry point). Invoking individual tests via a relative path (cd ~/.claude && bash hooks/foo.test.sh) is a FOOTGUN — it makes \$0 relative.
- Do NOT commit .sh source changes without staging the matching .test.sh.

COMPAT REQUIRED: if the script uses BSD/GNU-divergent commands (date -d/-r, stat -c/-f, readlink -f, echo -e, sed -i), it MUST source \$HOME/.claude/_lib/compat.sh and call the wrappers (_date_from_epoch, _file_mtime, _realpath_f, _echo_e, _sed_inplace) instead of the raw commands. In regexes, prefer POSIX character classes ([[:space:]], [[:alnum:]], [0-9]) over GNU extensions (\\s, \\w, \\d). See \$HOME/.claude/_lib/PORTABILITY.md for the full divergence table and per-script verification status.

(This reminder is generated by \$HOME/.claude/hooks/inject-shell-test-reminder.sh — edit that file to change the ruleset, or remove its wiring from \$HOME/.claude/settings.json to disable.)
EOF
)

jq -n --arg msg "$REMINDER" --arg sm "$SM" '{
  "systemMessage": $sm,
  "hookSpecificOutput": {
    "hookEventName": "PreToolUse",
    "additionalContext": $msg
  }
}'

exit 0
